# Generated by Django 4.2.21 on 2025-05-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_crawling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeproduct',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='youtubeproduct',
            name='product_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='product_count',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
