# Generated by Django 4.2.21 on 2025-05-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_crawling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='extracted_date',
            field=models.CharField(max_length=255),
        ),
    ]
