# Generated by Django 4.2.21 on 2025-05-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_crawling', '0002_alter_youtubevideo_extracted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeproduct',
            name='product_image_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubeproduct',
            name='product_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
